title: ModMate
description: A companion tool to help NUS students manage their modules effectively.
theme: just-the-docs

url: https://ay2425s2-cs2113-w12-1.github.io/tp

aux_links:
  ModMate on GitHub:
    - https://github.com/AY2425S2-CS2113-W12-1/tp

back_to_top: true
back_to_top_text: "Back to top"

# color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red
  note-to-reader:
    title: For CS2113 instructors and peers
    color: yellow