name: Notify Telegram group chat

on: [push, pull_request_target]

jobs:
  notify_telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Notify the commit on Telegram
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.BOT_TOKEN }}'
          chat_id: '${{ secrets.CHAT_ID }}'
