name: Notify Telegram

on:
  issue_comment:
      types: [created]
  issues:
      types: [opened, closed, reopened]
  pull_request:
      types: [opened, closed, reopened]

jobs:
  notify_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Notify the Telegram group chat
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.BOT_TOKEN }}'
          chat_id: '${{ secrets.CHAT_ID }}'
